#version 460
#extension GL_GOOGLE_include_directive : require

layout (push_constant) uniform PushConstant {
    uint c_0;
    uint c_1;
    uint c_2;
    uint c_3;
} push_constant;

layout (set = 0, binding = 0) buffer OutputBuffer {
    uint output_buffer[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;

    output_buffer[0] = push_constant.c_0;
    output_buffer[1] = push_constant.c_1;
    output_buffer[2] = push_constant.c_2;
    output_buffer[3] = push_constant.c_3;
}