#version 460
#extension GL_GOOGLE_include_directive : require

layout (constant_id = 0) const uint c_0 = 0;
layout (constant_id = 1) const uint c_1 = 0;
layout (constant_id = 2) const uint c_2 = 0;
layout (constant_id = 3) const uint c_3 = 0;

layout (set = 0, binding = 0) buffer OutputBuffer {
    uint output_buffer[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;

    output_buffer[0] = c_0;
    output_buffer[1] = c_1;
    output_buffer[2] = c_2;
    output_buffer[3] = c_3;
}