#version 460
#extension GL_GOOGLE_include_directive : require

#include "common.comp"

layout(set = 0, binding = 0) buffer InputBuffer {
    int inputData[];
};

layout(set = 1, binding = 0) buffer OutputBuffer {
    int outputData[];
};

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    outputData[idx] = int(gl_LocalInvocationID.x);
}